/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PhoneNumbersRouteImport } from './routes/phone-numbers'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as CallsIdRouteImport } from './routes/calls.$id'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperTasksRouteImport } from './routes/developer.tasks'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as DeveloperProjectsIndexRouteImport } from './routes/developer.projects.index'
import { Route as DeveloperProjectsIdRouteImport } from './routes/developer.projects.$id'
import { Route as DeveloperProjectsNewRouteImport } from './routes/developer.projects.new'
import { Route as DeveloperProjectsIdIndexRouteImport } from './routes/developer.projects.$id.index'
import { Route as DeveloperProjectsIdActivityRouteImport } from './routes/developer.projects.$id.activity'
import { Route as DeveloperProjectsIdArchitectureRouteImport } from './routes/developer.projects.$id.architecture'
import { Route as DeveloperProjectsIdCodingRouteImport } from './routes/developer.projects.$id.coding'
import { Route as DeveloperProjectsIdDebugRouteImport } from './routes/developer.projects.$id.debug'
import { Route as DeveloperProjectsIdDocumentationRouteImport } from './routes/developer.projects.$id.documentation'
import { Route as DeveloperProjectsIdFilesRouteImport } from './routes/developer.projects.$id.files'
import { Route as DeveloperProjectsIdReviewRouteImport } from './routes/developer.projects.$id.review'
import { Route as DeveloperProjectsIdSecurityRouteImport } from './routes/developer.projects.$id.security'
import { Route as DeveloperProjectsIdTestsRouteImport } from './routes/developer.projects.$id.tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneNumbersRoute = PhoneNumbersRouteImport.update({
  id: '/phone-numbers',
  path: '/phone-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIdRoute = CallsIdRouteImport.update({
  id: '/calls/$id',
  path: '/calls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperTasksRoute = DeveloperTasksRouteImport.update({
  id: '/developer/tasks',
  path: '/developer/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectsIndexRoute = DeveloperProjectsIndexRouteImport.update({
  id: '/developer/projects/',
  path: '/developer/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectsIdRoute = DeveloperProjectsIdRouteImport.update({
  id: '/developer/projects/$id',
  path: '/developer/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectsNewRoute = DeveloperProjectsNewRouteImport.update({
  id: '/developer/projects/new',
  path: '/developer/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectsIdIndexRoute =
  DeveloperProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdActivityRoute =
  DeveloperProjectsIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdArchitectureRoute =
  DeveloperProjectsIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdCodingRoute =
  DeveloperProjectsIdCodingRouteImport.update({
    id: '/coding',
    path: '/coding',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdDebugRoute =
  DeveloperProjectsIdDebugRouteImport.update({
    id: '/debug',
    path: '/debug',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdDocumentationRoute =
  DeveloperProjectsIdDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdFilesRoute =
  DeveloperProjectsIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdReviewRoute =
  DeveloperProjectsIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdSecurityRoute =
  DeveloperProjectsIdSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)
const DeveloperProjectsIdTestsRoute =
  DeveloperProjectsIdTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => DeveloperProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/phone-numbers': typeof PhoneNumbersRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/calls/$id': typeof CallsIdRoute
  '/developer/tasks': typeof DeveloperTasksRoute
  '/orders/$id': typeof OrdersIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/developer/projects/$id': typeof DeveloperProjectsIdRouteWithChildren
  '/developer/projects/new': typeof DeveloperProjectsNewRoute
  '/developer/projects/': typeof DeveloperProjectsIndexRoute
  '/developer/projects/$id/activity': typeof DeveloperProjectsIdActivityRoute
  '/developer/projects/$id/architecture': typeof DeveloperProjectsIdArchitectureRoute
  '/developer/projects/$id/coding': typeof DeveloperProjectsIdCodingRoute
  '/developer/projects/$id/debug': typeof DeveloperProjectsIdDebugRoute
  '/developer/projects/$id/documentation': typeof DeveloperProjectsIdDocumentationRoute
  '/developer/projects/$id/files': typeof DeveloperProjectsIdFilesRoute
  '/developer/projects/$id/review': typeof DeveloperProjectsIdReviewRoute
  '/developer/projects/$id/security': typeof DeveloperProjectsIdSecurityRoute
  '/developer/projects/$id/tests': typeof DeveloperProjectsIdTestsRoute
  '/developer/projects/$id/': typeof DeveloperProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/phone-numbers': typeof PhoneNumbersRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/calls/$id': typeof CallsIdRoute
  '/developer/tasks': typeof DeveloperTasksRoute
  '/orders/$id': typeof OrdersIdRoute
  '/agents': typeof AgentsIndexRoute
  '/calls': typeof CallsIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/developer/projects/new': typeof DeveloperProjectsNewRoute
  '/developer/projects': typeof DeveloperProjectsIndexRoute
  '/developer/projects/$id/activity': typeof DeveloperProjectsIdActivityRoute
  '/developer/projects/$id/architecture': typeof DeveloperProjectsIdArchitectureRoute
  '/developer/projects/$id/coding': typeof DeveloperProjectsIdCodingRoute
  '/developer/projects/$id/debug': typeof DeveloperProjectsIdDebugRoute
  '/developer/projects/$id/documentation': typeof DeveloperProjectsIdDocumentationRoute
  '/developer/projects/$id/files': typeof DeveloperProjectsIdFilesRoute
  '/developer/projects/$id/review': typeof DeveloperProjectsIdReviewRoute
  '/developer/projects/$id/security': typeof DeveloperProjectsIdSecurityRoute
  '/developer/projects/$id/tests': typeof DeveloperProjectsIdTestsRoute
  '/developer/projects/$id': typeof DeveloperProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/phone-numbers': typeof PhoneNumbersRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/calls/$id': typeof CallsIdRoute
  '/developer/tasks': typeof DeveloperTasksRoute
  '/orders/$id': typeof OrdersIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/developer/projects/$id': typeof DeveloperProjectsIdRouteWithChildren
  '/developer/projects/new': typeof DeveloperProjectsNewRoute
  '/developer/projects/': typeof DeveloperProjectsIndexRoute
  '/developer/projects/$id/activity': typeof DeveloperProjectsIdActivityRoute
  '/developer/projects/$id/architecture': typeof DeveloperProjectsIdArchitectureRoute
  '/developer/projects/$id/coding': typeof DeveloperProjectsIdCodingRoute
  '/developer/projects/$id/debug': typeof DeveloperProjectsIdDebugRoute
  '/developer/projects/$id/documentation': typeof DeveloperProjectsIdDocumentationRoute
  '/developer/projects/$id/files': typeof DeveloperProjectsIdFilesRoute
  '/developer/projects/$id/review': typeof DeveloperProjectsIdReviewRoute
  '/developer/projects/$id/security': typeof DeveloperProjectsIdSecurityRoute
  '/developer/projects/$id/tests': typeof DeveloperProjectsIdTestsRoute
  '/developer/projects/$id/': typeof DeveloperProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/appointments'
    | '/auth'
    | '/catalog'
    | '/mcp'
    | '/onboarding'
    | '/phone-numbers'
    | '/recordings'
    | '/settings'
    | '/team'
    | '/templates'
    | '/usage'
    | '/webhooks'
    | '/.well-known/oauth-protected-resource'
    | '/agents/$id'
    | '/agents/new'
    | '/calls/$id'
    | '/developer/tasks'
    | '/orders/$id'
    | '/agents/'
    | '/calls/'
    | '/developer/'
    | '/orders/'
    | '/developer/projects/$id'
    | '/developer/projects/new'
    | '/developer/projects/'
    | '/developer/projects/$id/activity'
    | '/developer/projects/$id/architecture'
    | '/developer/projects/$id/coding'
    | '/developer/projects/$id/debug'
    | '/developer/projects/$id/documentation'
    | '/developer/projects/$id/files'
    | '/developer/projects/$id/review'
    | '/developer/projects/$id/security'
    | '/developer/projects/$id/tests'
    | '/developer/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/appointments'
    | '/auth'
    | '/catalog'
    | '/mcp'
    | '/onboarding'
    | '/phone-numbers'
    | '/recordings'
    | '/settings'
    | '/team'
    | '/templates'
    | '/usage'
    | '/webhooks'
    | '/.well-known/oauth-protected-resource'
    | '/agents/$id'
    | '/agents/new'
    | '/calls/$id'
    | '/developer/tasks'
    | '/orders/$id'
    | '/agents'
    | '/calls'
    | '/developer'
    | '/orders'
    | '/developer/projects/new'
    | '/developer/projects'
    | '/developer/projects/$id/activity'
    | '/developer/projects/$id/architecture'
    | '/developer/projects/$id/coding'
    | '/developer/projects/$id/debug'
    | '/developer/projects/$id/documentation'
    | '/developer/projects/$id/files'
    | '/developer/projects/$id/review'
    | '/developer/projects/$id/security'
    | '/developer/projects/$id/tests'
    | '/developer/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/appointments'
    | '/auth'
    | '/catalog'
    | '/mcp'
    | '/onboarding'
    | '/phone-numbers'
    | '/recordings'
    | '/settings'
    | '/team'
    | '/templates'
    | '/usage'
    | '/webhooks'
    | '/.well-known/oauth-protected-resource'
    | '/agents/$id'
    | '/agents/new'
    | '/calls/$id'
    | '/developer/tasks'
    | '/orders/$id'
    | '/agents/'
    | '/calls/'
    | '/developer/'
    | '/orders/'
    | '/developer/projects/$id'
    | '/developer/projects/new'
    | '/developer/projects/'
    | '/developer/projects/$id/activity'
    | '/developer/projects/$id/architecture'
    | '/developer/projects/$id/coding'
    | '/developer/projects/$id/debug'
    | '/developer/projects/$id/documentation'
    | '/developer/projects/$id/files'
    | '/developer/projects/$id/review'
    | '/developer/projects/$id/security'
    | '/developer/projects/$id/tests'
    | '/developer/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PhoneNumbersRoute: typeof PhoneNumbersRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
  UsageRoute: typeof UsageRoute
  WebhooksRoute: typeof WebhooksRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  CallsIdRoute: typeof CallsIdRoute
  DeveloperTasksRoute: typeof DeveloperTasksRoute
  OrdersIdRoute: typeof OrdersIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CallsIndexRoute: typeof CallsIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  DeveloperProjectsIdRoute: typeof DeveloperProjectsIdRouteWithChildren
  DeveloperProjectsNewRoute: typeof DeveloperProjectsNewRoute
  DeveloperProjectsIndexRoute: typeof DeveloperProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-numbers': {
      id: '/phone-numbers'
      path: '/phone-numbers'
      fullPath: '/phone-numbers'
      preLoaderRoute: typeof PhoneNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$id': {
      id: '/calls/$id'
      path: '/calls/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof CallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/tasks': {
      id: '/developer/tasks'
      path: '/developer/tasks'
      fullPath: '/developer/tasks'
      preLoaderRoute: typeof DeveloperTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/projects/': {
      id: '/developer/projects/'
      path: '/developer/projects'
      fullPath: '/developer/projects/'
      preLoaderRoute: typeof DeveloperProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/projects/$id': {
      id: '/developer/projects/$id'
      path: '/developer/projects/$id'
      fullPath: '/developer/projects/$id'
      preLoaderRoute: typeof DeveloperProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/projects/new': {
      id: '/developer/projects/new'
      path: '/developer/projects/new'
      fullPath: '/developer/projects/new'
      preLoaderRoute: typeof DeveloperProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/projects/$id/': {
      id: '/developer/projects/$id/'
      path: '/'
      fullPath: '/developer/projects/$id/'
      preLoaderRoute: typeof DeveloperProjectsIdIndexRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/activity': {
      id: '/developer/projects/$id/activity'
      path: '/activity'
      fullPath: '/developer/projects/$id/activity'
      preLoaderRoute: typeof DeveloperProjectsIdActivityRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/architecture': {
      id: '/developer/projects/$id/architecture'
      path: '/architecture'
      fullPath: '/developer/projects/$id/architecture'
      preLoaderRoute: typeof DeveloperProjectsIdArchitectureRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/coding': {
      id: '/developer/projects/$id/coding'
      path: '/coding'
      fullPath: '/developer/projects/$id/coding'
      preLoaderRoute: typeof DeveloperProjectsIdCodingRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/debug': {
      id: '/developer/projects/$id/debug'
      path: '/debug'
      fullPath: '/developer/projects/$id/debug'
      preLoaderRoute: typeof DeveloperProjectsIdDebugRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/documentation': {
      id: '/developer/projects/$id/documentation'
      path: '/documentation'
      fullPath: '/developer/projects/$id/documentation'
      preLoaderRoute: typeof DeveloperProjectsIdDocumentationRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/files': {
      id: '/developer/projects/$id/files'
      path: '/files'
      fullPath: '/developer/projects/$id/files'
      preLoaderRoute: typeof DeveloperProjectsIdFilesRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/review': {
      id: '/developer/projects/$id/review'
      path: '/review'
      fullPath: '/developer/projects/$id/review'
      preLoaderRoute: typeof DeveloperProjectsIdReviewRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/security': {
      id: '/developer/projects/$id/security'
      path: '/security'
      fullPath: '/developer/projects/$id/security'
      preLoaderRoute: typeof DeveloperProjectsIdSecurityRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
    '/developer/projects/$id/tests': {
      id: '/developer/projects/$id/tests'
      path: '/tests'
      fullPath: '/developer/projects/$id/tests'
      preLoaderRoute: typeof DeveloperProjectsIdTestsRouteImport
      parentRoute: typeof DeveloperProjectsIdRoute
    }
  }
}

interface DeveloperProjectsIdRouteChildren {
  DeveloperProjectsIdActivityRoute: typeof DeveloperProjectsIdActivityRoute
  DeveloperProjectsIdArchitectureRoute: typeof DeveloperProjectsIdArchitectureRoute
  DeveloperProjectsIdCodingRoute: typeof DeveloperProjectsIdCodingRoute
  DeveloperProjectsIdDebugRoute: typeof DeveloperProjectsIdDebugRoute
  DeveloperProjectsIdDocumentationRoute: typeof DeveloperProjectsIdDocumentationRoute
  DeveloperProjectsIdFilesRoute: typeof DeveloperProjectsIdFilesRoute
  DeveloperProjectsIdReviewRoute: typeof DeveloperProjectsIdReviewRoute
  DeveloperProjectsIdSecurityRoute: typeof DeveloperProjectsIdSecurityRoute
  DeveloperProjectsIdTestsRoute: typeof DeveloperProjectsIdTestsRoute
  DeveloperProjectsIdIndexRoute: typeof DeveloperProjectsIdIndexRoute
}

const DeveloperProjectsIdRouteChildren: DeveloperProjectsIdRouteChildren = {
  DeveloperProjectsIdActivityRoute: DeveloperProjectsIdActivityRoute,
  DeveloperProjectsIdArchitectureRoute: DeveloperProjectsIdArchitectureRoute,
  DeveloperProjectsIdCodingRoute: DeveloperProjectsIdCodingRoute,
  DeveloperProjectsIdDebugRoute: DeveloperProjectsIdDebugRoute,
  DeveloperProjectsIdDocumentationRoute: DeveloperProjectsIdDocumentationRoute,
  DeveloperProjectsIdFilesRoute: DeveloperProjectsIdFilesRoute,
  DeveloperProjectsIdReviewRoute: DeveloperProjectsIdReviewRoute,
  DeveloperProjectsIdSecurityRoute: DeveloperProjectsIdSecurityRoute,
  DeveloperProjectsIdTestsRoute: DeveloperProjectsIdTestsRoute,
  DeveloperProjectsIdIndexRoute: DeveloperProjectsIdIndexRoute,
}

const DeveloperProjectsIdRouteWithChildren =
  DeveloperProjectsIdRoute._addFileChildren(DeveloperProjectsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PhoneNumbersRoute: PhoneNumbersRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
  UsageRoute: UsageRoute,
  WebhooksRoute: WebhooksRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AgentsIdRoute: AgentsIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  CallsIdRoute: CallsIdRoute,
  DeveloperTasksRoute: DeveloperTasksRoute,
  OrdersIdRoute: OrdersIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CallsIndexRoute: CallsIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  DeveloperProjectsIdRoute: DeveloperProjectsIdRouteWithChildren,
  DeveloperProjectsNewRoute: DeveloperProjectsNewRoute,
  DeveloperProjectsIndexRoute: DeveloperProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
